# This rule is not used by the project resource-autoscaler-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over autoscaling.baniasadi.autoscaling.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resource-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcescalerpolicy-admin-role
rules:
- apiGroups:
  - autoscaling.baniasadi.autoscaling.io
  resources:
  - resourcescalerpolicies
  verbs:
  - '*'
- apiGroups:
  - autoscaling.baniasadi.autoscaling.io
  resources:
  - resourcescalerpolicies/status
  verbs:
  - get
